export const UserAccessCodeEnum = {
  View_Base_Info_Menu: 0,
  Manage_Countrys: 1,
  Manage_Cities: 2,
  Manage_Categories: 3,
  Manage_Brands: 4,
  Manage_Shop: 5,
  Manage_Time_Sending: 6,
  Manage_Group: 7,
  Manage_Settings: 8,
  Manage_Product: 9,
  Manage_ApplicationUser: 10,
  Manage_Order: 11,
  View_Advertising_Menu: 12,
  Manage_Advertising: 13,
  Manage_Adver_Categories_And_Features: 14,
  View_Footer_Menu: 15,
  Manage_Edit_Term_And_Conditions: 16,
  Manage_Edit_FAQ: 17,
  Manage_Edit_Help: 18,
};
